openapi: 3.0.3
info:
  version: 1.0.0
  title: 창작지원 API Docs
  description: 창작지원 API 문서입니다.
servers:
  - url: http://localhost:3000
paths:
  $ref: "./paths/_index.yaml"

components: {
      securitySchemes: {
        jwt: {
          type: "http",
          scheme: "basic",
          in: "header",
          bearerFormat: "JWT"
        },
      }
    }
security: [{
      jwt: []
}]